### ISSUE TITLE
faq component needs some work

### ISSUE THREAD

**Issue by Highfire1** [langaracpsc/lhacks2024#5]
source actual questions and answers from other hackathon websites
- e.g. do you need to bring food, will there be parking reimbursements

component should be centered

**Comment by Highfire1** [comment]
you can copy last years faq: https://www.langaracs.ca/hacks

**Comment by FelipeBarrosCode** [comment]
Fixed Added the chage color in the arrow and the text when clicked and the Accordion only push down the items in the same column

**Comment by Highfire1** [comment]
resolved in multiple commits
