### ISSUE TITLE
Weird spacing under sponsor logos

### ISSUE THREAD

**Issue by Highfire1** [langaracpsc/lhacks2024#6]
not sure what is causing this spacing but it shouldn't be there
![image](https://github.com/langaracpsc/lhacks2024/assets/45698812/4892fffb-29dc-40e2-bc91-097d255c4995)

**Comment by FelipeBarrosCode** [comment]
Fixeed it just removed the pas.size from the parent div on each image. Make it look like this.

![image](https://github.com/langaracpsc/lhacks2024/assets/103279945/b4341a0a-f003-4df5-b31a-b0d31203b5dc)
