### ISSUE TITLE
Orange bars on the timeline arrow are not aligned with the important dates

### ISSUE THREAD

**Issue by FelipeBarrosCode** [langaracpsc/lhacks2024#8]
![Why not just do a image on gimp](https://github.com/langaracpsc/lhacks2024/assets/103279945/ef3d4623-8164-40ac-a1e9-d5fa7500bc06)
Why somebody doesn't make this an image on gimp with transparent background?

If we did that we could: 
1. Improve alignment of txt
2. Easier to manipulate

**Comment by Highfire1** [comment]
edited the title because I couldn't tell what that meant at first

You can probably just increase the gap between the date fields, since that whole part disappears if the screen isn't wide enough, generally you don't want to make text an image since it makes it non-copyable

**Comment by rishit-singh** [comment]
Fixed
